from __future__ import annotations
from typing import Protocol, runtime_checkable
from app.models.user import User, LifestylePreferences
from app.models.property import Property
from app.models.booking import Booking
from app.models.review import Review
from app.models.notification import Notification
from app.models.conversation import Conversation, Message
from app.models.amenity import AmenityCategory
from app.models.connection_request import ConnectionRequest


@runtime_checkable
class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_all(self) -> list[User]: ...
    def create(self, user: User) -> User: ...
    def update_profile(self, user_id: int, first_name: str, last_name: str, phone: str, bio: str) -> User | None: ...
    def update_personal_info(self, user_id: int, email: str, phone: str) -> User | None: ...
    def update_preferences(self, user_id: int, prefs: LifestylePreferences) -> User | None: ...
    def next_id(self) -> int: ...


@runtime_checkable
class PropertyRepository(Protocol):
    def get_by_id(self, property_id: int) -> Property | None: ...
    def get_all_active(self) -> list[Property]: ...
    def get_by_host_id(self, host_id: int) -> list[Property]: ...
    def search(
        self,
        district: str | None,
        room_type: str | None,
        nearest_university: str | None,
        min_price_per_month: float | None,
        max_price_per_month: float | None,
        capacity: int | None,
        amenities: list[str] | None,
        query: str | None,
        pets_allowed: bool | None,
        quiet_hours: bool | None,
        has_workspace: bool | None,
    ) -> list[Property]: ...
    def create(self, prop: Property) -> Property: ...
    def next_id(self) -> int: ...


@runtime_checkable
class BookingRepository(Protocol):
    def get_by_tenant_id(self, tenant_id: int) -> list[Booking]: ...
    def get_by_host_id(self, host_id: int) -> list[Booking]: ...
    def get_by_id(self, booking_id: int) -> Booking | None: ...
    def create(self, booking: Booking) -> Booking: ...
    def update_status(self, booking_id: int, status: str) -> Booking | None: ...
    def next_id(self) -> int: ...


@runtime_checkable
class ReviewRepository(Protocol):
    def get_by_property_id(self, property_id: int) -> list[Review]: ...
    def get_by_property_ids(self, property_ids: list[int]) -> list[Review]: ...
    def create(self, review: Review) -> Review: ...
    def next_id(self) -> int: ...


@runtime_checkable
class NotificationRepository(Protocol):
    def get_by_user_id(self, user_id: int) -> list[Notification]: ...
    def mark_read(self, notification_id: int) -> Notification | None: ...


@runtime_checkable
class ConversationRepository(Protocol):
    def get_by_user_id(self, user_id: int) -> list[Conversation]: ...
    def get_by_id(self, conversation_id: int) -> Conversation | None: ...
    def add_message(self, conversation_id: int, message: Message) -> Conversation | None: ...
    def next_message_id(self) -> int: ...
    def create(self, conversation: Conversation) -> Conversation: ...
    def next_id(self) -> int: ...


@runtime_checkable
class AmenityRepository(Protocol):
    def get_all_categories(self) -> list[AmenityCategory]: ...


@runtime_checkable
class ConnectionRequestRepository(Protocol):
    def next_id(self) -> int: ...
    def create(self, req: ConnectionRequest) -> ConnectionRequest: ...
    def get_by_id(self, req_id: int) -> ConnectionRequest | None: ...
    def get_incoming(self, user_id: int) -> list[ConnectionRequest]: ...
    def set_status(self, req_id: int, status: str) -> ConnectionRequest | None: ...
