from app.models.booking import Booking

BOOKINGS: list[Booking] = [
    Booking(
        id=1,
        property_id=1,
        tenant_id=1,
        host_id=2,
        start_month="2026-03",
        duration_months=6,
        resident_count=1,
        price_per_month=550.0,
        service_fee=462.0,
        total_amount=3762.0,
        currency="PEN",
        status="confirmed",
        guest_message="Hola, soy estudiante de la PUCP y busco un lugar tranquilo para el ciclo 2026-1. Me comprometo a cuidar el espacio.",
        host_note=None,
        created_at="2026-02-10",
    ),
    Booking(
        id=2,
        property_id=2,
        tenant_id=3,
        host_id=2,
        start_month="2026-08",
        duration_months=3,
        resident_count=1,
        price_per_month=750.0,
        service_fee=315.0,
        total_amount=2565.0,
        currency="PEN",
        status="confirmed",
        guest_message="Estudiante de la UNI, muy ordenada y responsable. Busco un lugar cerca del campus para el ciclo 2026-2.",
        host_note="Documentos verificados, bienvenida.",
        created_at="2026-07-01",
    ),
    Booking(
        id=3,
        property_id=5,
        tenant_id=1,
        host_id=2,
        start_month="2025-09",
        duration_months=12,
        resident_count=1,
        price_per_month=900.0,
        service_fee=1512.0,
        total_amount=12312.0,
        currency="PEN",
        status="completed",
        guest_message="Año académico completo 2025. Muy interesada en la habitación de Miraflores.",
        host_note=None,
        created_at="2025-08-20",
    ),
    Booking(
        id=4,
        property_id=4,
        tenant_id=3,
        host_id=2,
        start_month="2026-01",
        duration_months=3,
        resident_count=1,
        price_per_month=1200.0,
        service_fee=504.0,
        total_amount=4104.0,
        currency="PEN",
        status="cancelled",
        guest_message="Interesada en el departamento de La Molina para el primer ciclo del año.",
        host_note="Cancelado por el estudiante antes del ingreso.",
        created_at="2025-12-15",
    ),
]
