from app.models.property import Property

PROPERTIES: list[Property] = [
    Property(
        id=1,
        host_id=2,
        title="Habitación individual cerca de PUCP",
        description="Habitación luminosa en departamento compartido en San Miguel, a 10 minutos caminando de la PUCP. El departamento cuenta con sala, cocina equipada y terraza. Ideal para estudiantes que buscan tranquilidad y un espacio propio para estudiar.",
        short_description="Habitación en San Miguel, 10 min a pie de PUCP",
        room_type="room",
        price_per_month=550.0,
        price_per_night=0.0,
        currency="PEN",
        location="Av. La Marina 2350",
        district="San Miguel",
        city="Lima",
        country="Perú",
        lat=-12.0771,
        lng=-77.0842,
        images=[
            "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "WASHER", "WORKSPACE", "QUIET_HOURS"],
        capacity=1,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        checkin_time="14:00",
        checkout_time="12:00",
        house_rules=[
            "No fumar dentro del departamento",
            "Horario de silencio a partir de las 10:00 pm",
            "No mascotas",
            "Visitas hasta las 9:00 pm",
        ],
        status="active",
        availability_status="available",
        verified_host=True,
        nearest_university="PUCP",
        distance_to_university_minutes=10,
        created_at="2025-08-01",
    ),
    Property(
        id=2,
        host_id=2,
        title="Estudio amoblado en Rímac — cerca UNI",
        description="Estudio moderno completamente amoblado en el Rímac, a 8 minutos en bus del campus UNI. Incluye kitchenette, baño privado y zona de escritorio. Servicios de agua, luz e internet incluidos en el precio mensual.",
        short_description="Estudio independiente, 8 min a UNI — servicios incluidos",
        room_type="studio",
        price_per_month=750.0,
        price_per_night=0.0,
        currency="PEN",
        location="Jr. Trujillo 450",
        district="Rímac",
        city="Lima",
        country="Perú",
        lat=-12.0272,
        lng=-77.0347,
        images=[
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
            "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "HOT_WATER", "WORKSPACE", "TV"],
        capacity=1,
        bedrooms=0,
        beds=1,
        bathrooms=1,
        checkin_time="15:00",
        checkout_time="11:00",
        house_rules=[
            "Solo para estudiantes universitarios",
            "No fiestas ni reuniones ruidosas",
            "No fumar",
        ],
        status="active",
        availability_status="available",
        verified_host=True,
        nearest_university="UNI",
        distance_to_university_minutes=8,
        created_at="2025-09-15",
    ),
    Property(
        id=3,
        host_id=2,
        title="Cuarto en casa compartida — Surco, cerca UPC",
        description="Habitación en casa familiar compartida con otros 2 estudiantes en Santiago de Surco. A 5 minutos en combi de la UPC. Ambiente familiar y tranquilo. Limpieza rotativa de áreas comunes.",
        short_description="Habitación compartida, 5 min a UPC — ambiente familiar",
        room_type="shared",
        price_per_month=450.0,
        price_per_night=0.0,
        currency="PEN",
        location="Calle Los Manzanos 180",
        district="Santiago de Surco",
        city="Lima",
        country="Perú",
        lat=-12.1465,
        lng=-76.9934,
        images=[
            "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800",
            "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "WASHER", "PARKING", "PETS_ALLOWED"],
        capacity=1,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        checkin_time="14:00",
        checkout_time="12:00",
        house_rules=[
            "Limpieza rotativa de cocina y sala",
            "Avisar con 48h si recibes visitas",
            "Respetar espacios comunes",
        ],
        status="active",
        availability_status="reserved",
        verified_host=False,
        nearest_university="UPC",
        distance_to_university_minutes=5,
        created_at="2025-07-20",
    ),
    Property(
        id=4,
        host_id=2,
        title="Departamento moderno en La Molina — cerca ULIMA",
        description="Departamento de un dormitorio completamente equipado en La Molina. A 12 minutos caminando de la Universidad de Lima. Edificio con seguridad 24h, área de coworking en el lobby y estacionamiento disponible.",
        short_description="Depa 1 dorm en La Molina, 12 min a ULIMA — seguridad 24h",
        room_type="apartment",
        price_per_month=1200.0,
        price_per_night=0.0,
        currency="PEN",
        location="Av. La Fontana 1580",
        district="La Molina",
        city="Lima",
        country="Perú",
        lat=-12.0767,
        lng=-76.9336,
        images=[
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
            "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800",
        ],
        amenities=["WIFI", "PARKING", "AIR_CONDITIONING", "KITCHEN", "WASHER", "WORKSPACE", "TV", "SMOKE_DETECTOR"],
        capacity=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        checkin_time="15:00",
        checkout_time="11:00",
        house_rules=[
            "No fumar en ninguna área del edificio",
            "Mascotas pequeñas permitidas con depósito",
            "Silencio entre 11 pm y 7 am",
        ],
        status="active",
        availability_status="available",
        verified_host=True,
        nearest_university="ULIMA",
        distance_to_university_minutes=12,
        created_at="2025-10-01",
    ),
    Property(
        id=5,
        host_id=2,
        title="Habitación en Miraflores — cerca UP",
        description="Habitación en departamento ejecutivo en Miraflores, zona céntrica y segura. Muy cerca de la Universidad del Pacífico. Comparte apartamento con 1 profesional joven. Internet fibra óptica, vista al parque.",
        short_description="Habitación ejecutiva en Miraflores, 7 min a UP",
        room_type="room",
        price_per_month=900.0,
        price_per_night=0.0,
        currency="PEN",
        location="Calle Schell 390",
        district="Miraflores",
        city="Lima",
        country="Perú",
        lat=-12.1219,
        lng=-77.0282,
        images=[
            "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800",
            "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "WASHER", "WORKSPACE", "HOT_WATER", "TV", "QUIET_HOURS"],
        capacity=1,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        checkin_time="14:00",
        checkout_time="12:00",
        house_rules=[
            "Solo para estudiantes o jóvenes profesionales",
            "No fumar",
            "Silencio 11 pm en adelante",
            "No mascotas",
        ],
        status="active",
        availability_status="available",
        verified_host=True,
        nearest_university="UP",
        distance_to_university_minutes=7,
        created_at="2025-09-01",
    ),
    Property(
        id=6,
        host_id=2,
        title="Cuarto en Los Olivos — cerca USIL",
        description="Habitación amplia en Los Olivos a 6 minutos del campus de la USIL. Casa familiar con jardín. Propietaria vive en la misma casa. Ambiente seguro y tranquilo. Incluye desayuno de lunes a viernes.",
        short_description="Habitación con desayuno en Los Olivos, 6 min a USIL",
        room_type="room",
        price_per_month=600.0,
        price_per_night=0.0,
        currency="PEN",
        location="Av. Antúnez de Mayolo 780",
        district="Los Olivos",
        city="Lima",
        country="Perú",
        lat=-11.9977,
        lng=-77.0703,
        images=[
            "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800",
            "https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "WASHER", "BREAKFAST", "HOT_WATER", "PARKING"],
        capacity=1,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        checkin_time="14:00",
        checkout_time="12:00",
        house_rules=[
            "No visitas nocturnas",
            "Incluye desayuno L-V",
            "No fumar",
            "Curfew 11 pm",
        ],
        status="active",
        availability_status="unavailable",
        verified_host=False,
        nearest_university="USIL",
        distance_to_university_minutes=6,
        created_at="2025-06-15",
    ),
    Property(
        id=7,
        host_id=2,
        title="Estudio en Jesús María — cerca UNFV",
        description="Estudio independiente en Jesús María a 9 minutos en bus de la UNFV. Totalmente independiente con entrada propia. Baño y kitchenette completos. Edificio con cámaras de seguridad y recepción.",
        short_description="Estudio independiente en Jesús María, 9 min a UNFV",
        room_type="studio",
        price_per_month=680.0,
        price_per_night=0.0,
        currency="PEN",
        location="Av. Brasil 1540",
        district="Jesús María",
        city="Lima",
        country="Perú",
        lat=-12.0726,
        lng=-77.0530,
        images=[
            "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800",
            "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "HOT_WATER", "WORKSPACE", "SMOKE_DETECTOR"],
        capacity=1,
        bedrooms=0,
        beds=1,
        bathrooms=1,
        checkin_time="15:00",
        checkout_time="11:00",
        house_rules=[
            "Solo para estudiantes universitarios",
            "No fumar",
            "No fiestas",
        ],
        status="active",
        availability_status="available",
        verified_host=True,
        nearest_university="UNFV",
        distance_to_university_minutes=9,
        created_at="2025-10-20",
    ),
    Property(
        id=8,
        host_id=2,
        title="Departamento compartido en Bellavista — cerca UNAC",
        description="Departamento amplio para compartir entre 2 estudiantes en Bellavista, Callao. A 4 minutos caminando del campus de la UNAC. Dos habitaciones independientes, sala, cocina equipada y baño compartido. Muy buen precio para la zona.",
        short_description="Depa compartido en Bellavista, 4 min a UNAC — excelente precio",
        room_type="shared",
        price_per_month=480.0,
        price_per_night=0.0,
        currency="PEN",
        location="Jr. Constitución 890",
        district="Bellavista",
        city="Callao",
        country="Perú",
        lat=-12.0593,
        lng=-77.1130,
        images=[
            "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800",
        ],
        amenities=["WIFI", "KITCHEN", "WASHER", "PARKING", "WORKSPACE"],
        capacity=2,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        checkin_time="14:00",
        checkout_time="12:00",
        house_rules=[
            "Solo estudiantes de la UNAC o universidades cercanas",
            "Limpieza de áreas comunes semanal rotativa",
            "No fumar dentro",
        ],
        status="active",
        availability_status="available",
        verified_host=False,
        nearest_university="UNAC",
        distance_to_university_minutes=4,
        created_at="2025-11-01",
    ),
]
