from passlib.context import CryptContext
from app.models.user import User, LifestylePreferences

_pwd = CryptContext(schemes=["bcrypt"], deprecated="auto")
_HASH = _pwd.hash("password123")

USERS: list[User] = [
    User(
        id=1,
        email="ana.garcia@pucp.pe",
        hashed_password=_HASH,
        first_name="Ana",
        last_name="García",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=47",
        phone="+51 987 654 321",
        bio="Estudiante de Ingeniería Civil en la PUCP. Busco un lugar tranquilo cerca del campus para el ciclo 2026-2.",
        created_at="2025-03-10",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="early",
            study_habits="intense",
            noise_level="quiet",
            cleanliness="strict",
            guests_policy="occasionally",
            smoking_policy="no",
            pets_policy="no",
            target_university="PUCP",
            max_monthly_budget=800.0,
        ),
    ),
    User(
        id=2,
        email="carlos.mendoza@gmail.com",
        hashed_password=_HASH,
        first_name="Carlos",
        last_name="Mendoza",
        role="host",
        avatar_url="https://i.pravatar.cc/150?img=12",
        phone="+51 912 345 678",
        bio="Propietario de departamentos en Miraflores y San Isidro. Llevo 5 años alquilando a estudiantes universitarios.",
        created_at="2024-11-05",
        lifestyle_preferences=None,
    ),
    User(
        id=3,
        email="lucia.torres@uni.pe",
        hashed_password=_HASH,
        first_name="Lucía",
        last_name="Torres",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=23",
        phone="+51 965 432 100",
        bio="Estudiante de Ingeniería Electrónica en la UNI. Me adapto bien a distintos ambientes y soy muy ordenada.",
        created_at="2025-01-20",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="night",
            study_habits="moderate",
            noise_level="moderate",
            cleanliness="average",
            guests_policy="never",
            smoking_policy="no",
            pets_policy="yes",
            target_university="UNI",
            max_monthly_budget=600.0,
        ),
    ),
    User(
        id=4,
        email="diego.ramos@upc.pe",
        hashed_password=_HASH,
        first_name="Diego",
        last_name="Ramos",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=15",
        phone="+51 900 111 222",
        bio="Estudiante de Administración en la UPC. Ordenado y sociable.",
        created_at="2025-04-12",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="night",
            study_habits="moderate",
            noise_level="lively",
            cleanliness="average",
            guests_policy="often",
            smoking_policy="no",
            pets_policy="no",
            target_university="UPC",
            max_monthly_budget=700.0,
        ),
    ),
    User(
        id=5,
        email="valeria.chavez@unmsm.pe",
        hashed_password=_HASH,
        first_name="Valeria",
        last_name="Chávez",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=25",
        phone="+51 901 222 333",
        bio="Estudiante de Medicina en la UNMSM. Necesito silencio para estudiar.",
        created_at="2025-02-18",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="early",
            study_habits="intense",
            noise_level="quiet",
            cleanliness="strict",
            guests_policy="never",
            smoking_policy="no",
            pets_policy="no",
            target_university="UNMSM",
            max_monthly_budget=550.0,
        ),
    ),
    User(
        id=6,
        email="mateo.flores@pucp.pe",
        hashed_password=_HASH,
        first_name="Mateo",
        last_name="Flores",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=33",
        phone="+51 902 333 444",
        bio="Estudiante de Arquitectura en la PUCP. Flexible y relajado con el orden.",
        created_at="2025-05-02",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="flexible",
            study_habits="casual",
            noise_level="moderate",
            cleanliness="relaxed",
            guests_policy="occasionally",
            smoking_policy="outside",
            pets_policy="yes",
            target_university="PUCP",
            max_monthly_budget=650.0,
        ),
    ),
    User(
        id=7,
        email="camila.rojas@uni.pe",
        hashed_password=_HASH,
        first_name="Camila",
        last_name="Rojas",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=9",
        phone="+51 903 444 555",
        bio="Estudiante de Ingeniería Industrial en la UNI. Muy estricta con la limpieza.",
        created_at="2025-01-30",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="early",
            study_habits="intense",
            noise_level="quiet",
            cleanliness="strict",
            guests_policy="never",
            smoking_policy="no",
            pets_policy="no",
            target_university="UNI",
            max_monthly_budget=900.0,
        ),
    ),
    User(
        id=8,
        email="sebastian.paredes@upc.pe",
        hashed_password=_HASH,
        first_name="Sebastián",
        last_name="Paredes",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=51",
        phone="+51 904 555 666",
        bio="Estudiante de Marketing en la UPC. Vida social activa y flexible con horarios.",
        created_at="2025-03-22",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="night",
            study_habits="casual",
            noise_level="lively",
            cleanliness="relaxed",
            guests_policy="often",
            smoking_policy="yes",
            pets_policy="yes",
            target_university="UPC",
            max_monthly_budget=750.0,
        ),
    ),
    User(
        id=9,
        email="fernanda.quispe@unmsm.pe",
        hashed_password=_HASH,
        first_name="Fernanda",
        last_name="Quispe",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=28",
        phone="+51 905 666 777",
        bio="Estudiante de Biología en la UNMSM. Moderada en todos los aspectos.",
        created_at="2025-04-05",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="flexible",
            study_habits="moderate",
            noise_level="moderate",
            cleanliness="average",
            guests_policy="occasionally",
            smoking_policy="outside",
            pets_policy="no",
            target_university="UNMSM",
            max_monthly_budget=500.0,
        ),
    ),
    User(
        id=10,
        email="rodrigo.salazar@pucp.pe",
        hashed_password=_HASH,
        first_name="Rodrigo",
        last_name="Salazar",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=60",
        phone="+51 906 777 888",
        bio="Estudiante de Economía en la PUCP. Nocturno y le gusta el estudio intenso.",
        created_at="2025-02-14",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="night",
            study_habits="intense",
            noise_level="quiet",
            cleanliness="strict",
            guests_policy="never",
            smoking_policy="no",
            pets_policy="no",
            target_university="PUCP",
            max_monthly_budget=850.0,
        ),
    ),
    User(
        id=11,
        email="antonella.vargas@uni.pe",
        hashed_password=_HASH,
        first_name="Antonella",
        last_name="Vargas",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=44",
        phone="+51 907 888 999",
        bio="Estudiante de Ingeniería de Sistemas en la UNI. Relajada y sociable.",
        created_at="2025-05-19",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="flexible",
            study_habits="casual",
            noise_level="lively",
            cleanliness="relaxed",
            guests_policy="often",
            smoking_policy="outside",
            pets_policy="yes",
            target_university="UNI",
            max_monthly_budget=600.0,
        ),
    ),
    User(
        id=12,
        email="joaquin.medina@upc.pe",
        hashed_password=_HASH,
        first_name="Joaquín",
        last_name="Medina",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=17",
        phone="+51 908 999 000",
        bio="Estudiante de Diseño Gráfico en la UPC. Madrugador y ordenado.",
        created_at="2025-01-08",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="early",
            study_habits="moderate",
            noise_level="moderate",
            cleanliness="strict",
            guests_policy="occasionally",
            smoking_policy="no",
            pets_policy="no",
            target_university="UPC",
            max_monthly_budget=680.0,
        ),
    ),
    User(
        id=13,
        email="ximena.castillo@unmsm.pe",
        hashed_password=_HASH,
        first_name="Ximena",
        last_name="Castillo",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=36",
        phone="+51 909 000 111",
        bio="Estudiante de Derecho en la UNMSM. Estudiosa y tranquila.",
        created_at="2025-03-01",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="early",
            study_habits="intense",
            noise_level="quiet",
            cleanliness="average",
            guests_policy="never",
            smoking_policy="no",
            pets_policy="yes",
            target_university="UNMSM",
            max_monthly_budget=520.0,
        ),
    ),
    User(
        id=14,
        email="benjamin.leon@pucp.pe",
        hashed_password=_HASH,
        first_name="Benjamín",
        last_name="León",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=53",
        phone="+51 910 111 222",
        bio="Estudiante de Psicología en la PUCP. Sociable pero respeta el descanso.",
        created_at="2025-04-27",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="night",
            study_habits="casual",
            noise_level="lively",
            cleanliness="average",
            guests_policy="often",
            smoking_policy="yes",
            pets_policy="no",
            target_university="PUCP",
            max_monthly_budget=770.0,
        ),
    ),
    User(
        id=15,
        email="isabela.nunez@uni.pe",
        hashed_password=_HASH,
        first_name="Isabela",
        last_name="Núñez",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=41",
        phone="+51 911 222 333",
        bio="Estudiante de Ingeniería Mecánica en la UNI. Estricta y madrugadora.",
        created_at="2025-02-25",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="early",
            study_habits="intense",
            noise_level="quiet",
            cleanliness="strict",
            guests_policy="never",
            smoking_policy="no",
            pets_policy="no",
            target_university="UNI",
            max_monthly_budget=900.0,
        ),
    ),
    User(
        id=16,
        email="nicolas.aguirre@upc.pe",
        hashed_password=_HASH,
        first_name="Nicolás",
        last_name="Aguirre",
        role="tenant",
        avatar_url="https://i.pravatar.cc/150?img=6",
        phone="+51 912 333 444",
        bio="Estudiante de Ingeniería Industrial en la UPC. Relajado, con mascota y horario flexible.",
        created_at="2025-05-30",
        lifestyle_preferences=LifestylePreferences(
            sleep_schedule="flexible",
            study_habits="moderate",
            noise_level="lively",
            cleanliness="relaxed",
            guests_policy="often",
            smoking_policy="outside",
            pets_policy="yes",
            target_university="UPC",
            max_monthly_budget=630.0,
        ),
    ),
]
