import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StepHeader } from '@/shared/components/ui/StepHeader';
import { WizardNav } from './WizardNav';
import { formatCurrency } from '@/shared/utils/formatters';
export const Step8Price = ({ draft, update, onNext, onPrev }) => {
    const serviceFee = Math.round(draft.pricePerNight * 0.14);
    const guestPays = draft.pricePerNight + serviceFee;
    return (_jsxs("div", { children: [_jsx(StepHeader, { current: 8, total: 9, title: "Establece tu precio por noche", subtitle: "Puedes ajustarlo en cualquier momento." }), _jsxs("div", { className: "mb-6 flex flex-col items-center gap-4", children: [_jsxs("div", { className: "relative", children: [_jsx("span", { className: "absolute left-4 top-1/2 -translate-y-1/2 text-2xl font-bold text-gray-400", children: "S/" }), _jsx("input", { type: "number", value: draft.pricePerNight, onChange: e => update({ pricePerNight: Math.max(1, Number(e.target.value)) }), className: "h-20 w-48 rounded-2xl border-2 border-gray-200 pl-14 pr-4 text-3xl font-bold text-gray-900 outline-none focus:border-blue-500", min: 1 })] }), _jsxs("div", { className: "w-full rounded-xl border border-gray-100 bg-gray-50 p-4 text-sm", children: [_jsxs("div", { className: "flex justify-between text-gray-600", children: [_jsx("span", { children: "Precio base" }), _jsx("span", { children: formatCurrency(draft.pricePerNight) })] }), _jsxs("div", { className: "flex justify-between text-gray-600", children: [_jsx("span", { children: "Tarifa de servicio (14%)" }), _jsx("span", { children: formatCurrency(serviceFee) })] }), _jsx("hr", { className: "my-2 border-gray-100" }), _jsxs("div", { className: "flex justify-between font-semibold text-gray-900", children: [_jsx("span", { children: "El hu\u00E9sped paga" }), _jsx("span", { children: formatCurrency(guestPays) })] })] })] }), _jsx(WizardNav, { onPrev: onPrev, onNext: onNext, canNext: draft.pricePerNight > 0 })] }));
};
