export { ProfilePage } from './pages/ProfilePage'
export { PersonalInfoPage } from './pages/PersonalInfoPage'
export { NotificationsPage } from './pages/NotificationsPage'
export { MessagesPage } from './pages/MessagesPage'
export { accountService } from './services/account.service'
export type { ProfileUpdatePayload, PersonalInfoPayload } from './types/account.types'
