export { PropertiesHomePage } from './pages/PropertiesHomePage'
export { SearchPage } from './pages/SearchPage'
export { PropertyDetailPage } from './pages/PropertyDetailPage'
export { PropertyCard } from './components/PropertyCard'
export { propertyService } from './services/property.service'
export type { Property, PropertySearchFilters, BookingDraft } from './types/property.types'
