import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Heart, Star, MapPin } from 'lucide-react';
import { cn } from '@/shared/utils/cn';
import { formatCurrency } from '@/shared/utils/formatters';
export const PropertyCard = ({ property }) => {
    const [liked, setLiked] = useState(false);
    return (_jsx("div", { className: "group overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm transition-shadow hover:shadow-md", children: _jsxs(Link, { to: `/properties/${property.id}`, className: "block", children: [_jsxs("div", { className: "relative h-48 overflow-hidden", children: [_jsx("img", { src: property.images[0], alt: property.title, className: "h-full w-full object-cover transition-transform duration-300 group-hover:scale-105" }), _jsx("button", { onClick: e => { e.preventDefault(); setLiked(v => !v); }, className: "absolute right-3 top-3 rounded-full bg-white/80 p-1.5 backdrop-blur-sm hover:bg-white", children: _jsx(Heart, { className: cn('h-4 w-4', liked ? 'fill-red-500 text-red-500' : 'text-gray-500') }) })] }), _jsxs("div", { className: "p-4", children: [_jsx("div", { className: "mb-1 flex items-start justify-between gap-2", children: _jsx("h3", { className: "line-clamp-2 text-sm font-semibold text-gray-900", children: property.title }) }), _jsxs("div", { className: "mb-2 flex items-center gap-1 text-xs text-gray-500", children: [_jsx(MapPin, { className: "h-3 w-3" }), property.district, ", ", property.city] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("span", { className: "font-semibold text-gray-900", children: formatCurrency(property.pricePerNight) }), _jsx("span", { className: "text-xs text-gray-500", children: " / noche" })] }), property.rating > 0 && (_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Star, { className: "h-3.5 w-3.5 fill-amber-400 text-amber-400" }), _jsx("span", { className: "text-sm font-medium text-gray-700", children: property.rating }), _jsxs("span", { className: "text-xs text-gray-400", children: ["(", property.reviewsCount, ")"] })] }))] })] })] }) }));
};
